<div class ="container">
    <div class="col-lg-1">

    </div>

    <div class="col-lg-11">
        <h3> Problemas abertos</h3>
        <div class ="table-responsive">
            <table class="table table-striped table-bordered table-hover table-condensed">
                <tr>


                    <th>Status</th>
                    <th>Problema</th>
                    <th>Obs</th>
                    <th>Maquina</th>
                    <th>Ações</th>

                </tr>



                <?php foreach($this->data as $entity): ?>
                    <tr>
                        <td><?php echo $entity->getStatus(); ?></td>
                        <td><?php echo $entity->getProblem(); ?></td>
                        <td><?php echo $entity->getObs(); ?></td>
                        <td><?php echo $entity->getObs(); ?></td>
                        <td>
                            <a href="<?php echo $this->url('pc_helpAdmin-interna',
                                array('controller'=>'solucao','action'=>'new','id'=>$entity->getCodOs())); ?>">Solucionar</a>
                            <a href="<?php echo $this->url('pc_helpAdmin-interna',
                                array('controller'=>'problema','action'=>'edit','id'=>$entity->getCodOs())); ?>">Atualizar</a>
                        </td>

                    </tr>
                <?php endforeach; ?>








            </table>

        </div> <!-- final table -->

    </div> <!-- final coll-lg-->
</div> <!--final container-->

</hr>





